on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Universal Pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CICD_TOKEN }}
          repository: creat-o-r/Firebase-GitHub
          event-type: pipeline
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'