on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -H "Authorization: token ${{ secrets.CICD_TOKEN }}" https://api.github.com/repos/creat-o-r/cicd-infrastructure/dispatches -d '{}'